name: Create EC2 instance

on:
  push:
    branches:
      - main
      
env:
  AWS_REGION: ap-south-1      

jobs:
  create-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: my-ec2-stack
          template: ./cloudformation/template.yaml
          parameter-overrides: KeyName=my-ec2-key-pair
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
